# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist: xenial
if: branch = master OR tag IS present OR type = pull_request
env:
  - JULIA_NUM_THREADS=2  # For testing multithreaded functions
julia:
  - 1.3
notifications:
  email: false
before_script:
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - julia --color=yes --project= -e 'using Pkg; Pkg.update()'  # Install General
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Lighthouse"); Pkg.test("Lighthouse"; coverage=true)'
codecov: true
after_success:
  - docs/build.sh
